### ISSUE TITLE
Don't compress tflite assets

### ISSUE THREAD

**Issue by jmayerbsd** [modular-ftc/robotcontroller-repackaged#9]
The built-in mechanism for loading `.tflite` files for `tfod` from assets requires that the `.tflite` files are not compressed. This could be added to the end user's gradle config, but the assets are "owned" by the `robotcontroller` and the mechanism for loading is internal to the SDK.
Currently I have to add this to my `TeamCode`'s `build.gradle`:
```gradle
android {
...
    aaptOptions {
        noCompress "tflite"
    }
...
}
```

**Comment by magneticflux-** [comment]
Thanks for bringing this to our attention, it seems we missed that addition when updating to 4.X. We're releasing a patch to address this issue (`4.3.1`).

**Comment by magneticflux-** [comment]
Version `4.3.1` should be fully available on Jitpack now.
